sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGbiwn2E5bzMmQBT5QS
    access-key-secret: 5ywCWb1ih4y3uJqNWcOSqjMhT8pnN9
    bucket-name: yuancb
  wechat:
    appid: wx4d7bf3880de238e6
    secret: 680a7dc6d9ba6bde6ca430f4b2617cad
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414A
    privateKeyFilePath: D:\Baidu
    api-v3-key: asdasd
    we-chat-pay-cert-file-path: adad
    notify-url:  https://20f1d017.r6.cpolar.top/notify/paySuccess
    refund-notify-url: https://20f1d017.r6.cpolar.top/notify/refundSuccess


spring:
  redis:
    host: localhost
    port: 6379
    database: 0
