sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    url: jdbc:mysql://localhost:3306/sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGbiwn2E5bzMmQBT5QS
    access-key-secret: 5ywCWb1ih4y3uJqNWcOSqjMhT8pnN9
    bucket-name: yuancb